title: "FAForever Balance Patchnotes"
description: "Latest balance updates for FAForever."
author: "FAForever Team"
lang: "en"
baseurl: ""
url: "https://faforever.github.io/FAFBalancePatchnotes"

# Build Settings
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-github-metadata
  - jekyll-paginate
  - jekyll-category-pages
  - jekyll-sitemap
  - jekyll-transcode-image-filters
  - jekyll-seo-tag

# markdown settings
markdown: kramdown
highlighter: rouge

# navigation
collections:
  posts:
    output: true
    permalink: /patches/:year/:month/:title

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .jekyll-cache
# Google Analytics
# google_analytics: UA-XXXXXXXX-X

social_links:
  twitter: "https://twitter.com/FAForever"
  github: "https://github.com/FAForever"
