title: "FAForever Balance Patchnotes"
url: "https://faforever.github.io/FAFBalancePatchnotes"
description: "Latest balance updates for FAForever."

permalink: FAF-Patchnotes-Site/:year/:month/:day/:title:output_ext

baseurl: ""

plugins_dir: _plugins
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-github-metadata
  - jekyll-sitemap
  - jekyll-category-pages
  - jekyll-transcode-image-filters
  - jekyll-paginate
  - jekyll-seo-tag

markdown: kramdown
highlighter: rouge

header_pages:
  - about.md

date_format: "%d %B, %Y"

repository: MrRowey/FAF-Patchnotes-Site

exclude:
  - .sass-cache/
  - .idea/
  - .vscode/
  - .gitignore
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
# Google Analytics
# google_analytics: UA-XXXXXXXX-X

social_links:
  twitter: "https://twitter.com/FAForever"
  github: "https://github.com/FAForever"

category_layout: category_index.html
category_path: category
