title: "FAForever Balance Patch Notes"
url: "https://mrrowey.github.io/FAF-Patchnotes-Site/"
description: "Stay up-to-date with the latest FAForever balance updates, patches, and game improvements."

permalink: "/:year/:month/:day/:title:output_ext"

# Base URL (Leave empty unless hosted in a subdirectory)
baseurl: "FAF-Patchnotes-Site/"

plugins_dir: _plugins
plugins:
  - jekyll-feed # Generates RSS feed
  - jekyll-redirect-from # Enables URL redirections
  - jekyll-github-metadata # Exposes repository metadata
  - jekyll-category-pages # Creates category pages
  - jekyll-sitemap # Generates sitemap for SEO

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - .jekyll-metadata
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - .gitignore
  - .idea/
  - .vscode/

header_pages:
  - about.md

date_format: "%d %B, %Y" # Example: "22 February, 2025"

repository: MrRowey/FAF-Patchnotes-Site

category_layout: category_index.html
category_path: category
