version: '3.8'  # Specify the version of Docker Compose

services:
  jekyll:
    image: ghcr.io/mrrowey/patchnotes-jekyll-environment:latest
    working_dir: /src
    command: sh -c "bundle install && bundle exec jekyll serve --host 0.0.0.0 --livereload --watch --incremental --force_polling"
    volumes:
      - ./src:/src:cached  # Use cached volume for improved performance on macOS/Windows
    ports:
      - "4000:4000"    # Jekyll server port
      - "35729:35729"  # LiveReload port
    environment:
      JEKYLL_ENV: development
      PAGES_REPO_NWO: MrRowey/FAF-Patchnotes-Site
    depends_on:
      - node  # Ensure Node service starts before Jekyll (if needed)
    networks:
      - devnetwork

  node:
    image: node:latest
    working_dir: /src
    command: sh -c "npm install && npm run watch"  # Example command for asset compilation
    volumes:
      - ./src:/src:cached
    networks:
      - devnetwork

volumes:
  src:

networks:
  devnetwork:
    driver: bridge