name: GitHub Pages - Deploy

on:
  # Enable this workflow to be triggered manually
  workflow_dispatch:

  # Enable this workflow to be triggered automatically
  push:
    branches:
      - deploy/gh-pages

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "github-pages"
  cancel-in-progress: true

jobs:
  build-and-minify:
    name: Build and minify the website
    uses: ./.github/workflows/jekyll-minify.yaml

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: [build-and-minify]
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          artifact_name: github-pages
