name: Jekyll - Build

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    name: Build Jekyll Site
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src
    container: ghcr.io/mrrowey/patchnotes-site-jekyll-environment:latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Set up caching for responsive images
      - name: Set Image Cache Name with Current Year
        id: cache-setup
        run: echo "IMAGE_CACHE_NAME=cache-images-$(date +'%Y')" >> $GITHUB_ENV

      - name: Restore Cached Images
        id: cache-images
        uses: actions/cache@v4
        with:
          path: cache
          key: ${{ env.IMAGE_CACHE_NAME }}-${{ runner.os }}-${{ hashFiles('assets/images/**') }}
          restore-keys: |
            ${{ env.IMAGE_CACHE_NAME }}-${{ runner.os }}-

      - name: Build with Jekyll
        env:
          JEKYLL_ENV: production
        run: |
          bundle install
          bundle exec jekyll build

      # List _site directory contents
      - name: List _site Directory
        run: ls -la _site

      # Upload the build artifact for continuous integration
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: src/_site/
